# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 600)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.display_area = QtWidgets.QFrame(self.centralwidget)
        self.display_area.setFrameShape(QtWidgets.QFrame.Panel)
        self.display_area.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.display_area.setObjectName("display_area")
        self.verticalLayout_2.addWidget(self.display_area)
        self.tool_line = QtWidgets.QHBoxLayout()
        self.tool_line.setObjectName("tool_line")
        self.control_area = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_area.sizePolicy().hasHeightForWidth())
        self.control_area.setSizePolicy(sizePolicy)
        self.control_area.setFrameShape(QtWidgets.QFrame.Box)
        self.control_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_area.setObjectName("control_area")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.control_area)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_back = QtWidgets.QComboBox(self.control_area)
        self.comboBox_back.setEditable(False)
        self.comboBox_back.setCurrentText("")
        self.comboBox_back.setObjectName("comboBox_back")
        self.horizontalLayout_3.addWidget(self.comboBox_back)
        self.pushButton_start = QtWidgets.QPushButton(self.control_area)
        icon = QtGui.QIcon.fromTheme("SP_MediaPlay")
        self.pushButton_start.setIcon(icon)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_3.addWidget(self.pushButton_start)
        self.pushButton_stop = QtWidgets.QPushButton(self.control_area)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_3.addWidget(self.pushButton_stop)
        self.pushButton_next_job = QtWidgets.QPushButton(self.control_area)
        self.pushButton_next_job.setObjectName("pushButton_next_job")
        self.horizontalLayout_3.addWidget(self.pushButton_next_job)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.box_automatic = QtWidgets.QCheckBox(self.control_area)
        self.box_automatic.setObjectName("box_automatic")
        self.horizontalLayout_3.addWidget(self.box_automatic)
        self.tool_line.addWidget(self.control_area)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tool_line.addItem(spacerItem1)
        self.label_current_progress = QtWidgets.QLabel(self.centralwidget)
        self.label_current_progress.setText("")
        self.label_current_progress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_current_progress.setObjectName("label_current_progress")
        self.tool_line.addWidget(self.label_current_progress)
        self.progressBar_current = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_current.setProperty("value", 0)
        self.progressBar_current.setObjectName("progressBar_current")
        self.tool_line.addWidget(self.progressBar_current)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tool_line.addItem(spacerItem2)
        self.label_batch_progress = QtWidgets.QLabel(self.centralwidget)
        self.label_batch_progress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_batch_progress.setObjectName("label_batch_progress")
        self.tool_line.addWidget(self.label_batch_progress)
        self.progressBar_batch = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_batch.setProperty("value", 0)
        self.progressBar_batch.setObjectName("progressBar_batch")
        self.tool_line.addWidget(self.progressBar_batch)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tool_line.addItem(spacerItem3)
        self.tool_line.setStretch(1, 3)
        self.tool_line.setStretch(2, 5)
        self.tool_line.setStretch(3, 12)
        self.tool_line.setStretch(4, 3)
        self.tool_line.setStretch(5, 3)
        self.tool_line.setStretch(6, 12)
        self.tool_line.setStretch(7, 12)
        self.verticalLayout_2.addLayout(self.tool_line)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionLoad_video_directory = QtWidgets.QAction(MainWindow)
        self.actionLoad_video_directory.setObjectName("actionLoad_video_directory")
        self.actionLoad_config = QtWidgets.QAction(MainWindow)
        self.actionLoad_config.setObjectName("actionLoad_config")
        self.actionSave_config = QtWidgets.QAction(MainWindow)
        self.actionSave_config.setObjectName("actionSave_config")
        self.actionLoad_postproc_config = QtWidgets.QAction(MainWindow)
        self.actionLoad_postproc_config.setObjectName("actionLoad_postproc_config")
        self.actionSave_postproc_config = QtWidgets.QAction(MainWindow)
        self.actionSave_postproc_config.setObjectName("actionSave_postproc_config")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionLoad_video_directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_config)
        self.menuFile.addAction(self.actionSave_config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_postproc_config)
        self.menuFile.addAction(self.actionSave_postproc_config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_back.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Planetary System Stacker"))
        self.pushButton_start.setText(_translate("MainWindow", "Start / Cont."))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_next_job.setText(_translate("MainWindow", "Next Job"))
        self.box_automatic.setText(_translate("MainWindow", "Automatic"))
        self.label_batch_progress.setText(_translate("MainWindow", "Batch progress"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_video_directory.setText(_translate("MainWindow", "Open"))
        self.actionLoad_config.setText(_translate("MainWindow", "Load stacking config"))
        self.actionSave_config.setText(_translate("MainWindow", "Save stacking config"))
        self.actionLoad_postproc_config.setText(_translate("MainWindow", "Load postproc config"))
        self.actionSave_postproc_config.setText(_translate("MainWindow", "Save postproc config"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

